# Use the official Golang image as the base
FROM golang:1.24

# Set the working directory inside the container
WORKDIR /app

# Copy the Go modules manifests and download dependencies
COPY go.mod go.sum ./
RUN go mod download

RUN export PATH=$(go env GOPATH)/bin:$PATH && \
    go install github.com/air-verse/air@latest

# Copy the source code
COPY . .

CMD ["air", "-c", ".air.toml"]