basePath: /
definitions:
  models.LoggedInUserResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  models.LoginUserRequest:
    properties:
      password:
        type: string
      uname:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      name:
        type: string
      password:
        type: string
      second:
        type: string
      uname:
        type: string
    type: object
info:
  contact:
    email: uOY9m@example.com
    name: API Support
    url: http://www.swagger.io/support
  description: JWT Auth API
  title: JWT Auth API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user using username and password, generates access
        and refresh tokens, and manages user sessions.
      parameters:
      - description: User login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoggedInUserResponse'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Not Found
          schema: {}
      summary: User login
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Creates a new user and sets up initial properties
      parameters:
      - description: User Registration Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
